//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSForm.FormReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSForm.FormReference.HelloWorldResponse HelloWorld(WSForm.FormReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSForm.FormReference.HelloWorldResponse> HelloWorldAsync(WSForm.FormReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtfFile", ReplyAction="*")]
        WSForm.FormReference.txtfFileResponse txtfFile(WSForm.FormReference.txtfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtfFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WSForm.FormReference.txtfFileResponse> txtfFileAsync(WSForm.FormReference.txtfFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSForm.FormReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSForm.FormReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSForm.FormReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSForm.FormReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txtfFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txtfFile", Namespace="http://tempuri.org/", Order=0)]
        public WSForm.FormReference.txtfFileRequestBody Body;
        
        public txtfFileRequest() {
        }
        
        public txtfFileRequest(WSForm.FormReference.txtfFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class txtfFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public txtfFileRequestBody() {
        }
        
        public txtfFileRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txtfFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txtfFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSForm.FormReference.txtfFileResponseBody Body;
        
        public txtfFileResponse() {
        }
        
        public txtfFileResponse(WSForm.FormReference.txtfFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class txtfFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string txtfFileResult;
        
        public txtfFileResponseBody() {
        }
        
        public txtfFileResponseBody(string txtfFileResult) {
            this.txtfFileResult = txtfFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WSForm.FormReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WSForm.FormReference.WebService1Soap>, WSForm.FormReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSForm.FormReference.HelloWorldResponse WSForm.FormReference.WebService1Soap.HelloWorld(WSForm.FormReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSForm.FormReference.HelloWorldRequest inValue = new WSForm.FormReference.HelloWorldRequest();
            inValue.Body = new WSForm.FormReference.HelloWorldRequestBody();
            WSForm.FormReference.HelloWorldResponse retVal = ((WSForm.FormReference.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSForm.FormReference.HelloWorldResponse> WSForm.FormReference.WebService1Soap.HelloWorldAsync(WSForm.FormReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSForm.FormReference.HelloWorldResponse> HelloWorldAsync() {
            WSForm.FormReference.HelloWorldRequest inValue = new WSForm.FormReference.HelloWorldRequest();
            inValue.Body = new WSForm.FormReference.HelloWorldRequestBody();
            return ((WSForm.FormReference.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSForm.FormReference.txtfFileResponse WSForm.FormReference.WebService1Soap.txtfFile(WSForm.FormReference.txtfFileRequest request) {
            return base.Channel.txtfFile(request);
        }
        
        public string txtfFile(string s) {
            WSForm.FormReference.txtfFileRequest inValue = new WSForm.FormReference.txtfFileRequest();
            inValue.Body = new WSForm.FormReference.txtfFileRequestBody();
            inValue.Body.s = s;
            WSForm.FormReference.txtfFileResponse retVal = ((WSForm.FormReference.WebService1Soap)(this)).txtfFile(inValue);
            return retVal.Body.txtfFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSForm.FormReference.txtfFileResponse> WSForm.FormReference.WebService1Soap.txtfFileAsync(WSForm.FormReference.txtfFileRequest request) {
            return base.Channel.txtfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSForm.FormReference.txtfFileResponse> txtfFileAsync(string s) {
            WSForm.FormReference.txtfFileRequest inValue = new WSForm.FormReference.txtfFileRequest();
            inValue.Body = new WSForm.FormReference.txtfFileRequestBody();
            inValue.Body.s = s;
            return ((WSForm.FormReference.WebService1Soap)(this)).txtfFileAsync(inValue);
        }
    }
}
