//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConsoleApp.WSPReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSConsoleApp.WSPReference.HelloWorldResponse HelloWorld(WSConsoleApp.WSPReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSConsoleApp.WSPReference.HelloWorldResponse> HelloWorldAsync(WSConsoleApp.WSPReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtfFile", ReplyAction="*")]
        WSConsoleApp.WSPReference.txtfFileResponse txtfFile(WSConsoleApp.WSPReference.txtfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txtfFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WSConsoleApp.WSPReference.txtfFileResponse> txtfFileAsync(WSConsoleApp.WSPReference.txtfFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSConsoleApp.WSPReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSConsoleApp.WSPReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSConsoleApp.WSPReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSConsoleApp.WSPReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txtfFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txtfFile", Namespace="http://tempuri.org/", Order=0)]
        public WSConsoleApp.WSPReference.txtfFileRequestBody Body;
        
        public txtfFileRequest() {
        }
        
        public txtfFileRequest(WSConsoleApp.WSPReference.txtfFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class txtfFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public txtfFileRequestBody() {
        }
        
        public txtfFileRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class txtfFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="txtfFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSConsoleApp.WSPReference.txtfFileResponseBody Body;
        
        public txtfFileResponse() {
        }
        
        public txtfFileResponse(WSConsoleApp.WSPReference.txtfFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class txtfFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string txtfFileResult;
        
        public txtfFileResponseBody() {
        }
        
        public txtfFileResponseBody(string txtfFileResult) {
            this.txtfFileResult = txtfFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WSConsoleApp.WSPReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WSConsoleApp.WSPReference.WebService1Soap>, WSConsoleApp.WSPReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleApp.WSPReference.HelloWorldResponse WSConsoleApp.WSPReference.WebService1Soap.HelloWorld(WSConsoleApp.WSPReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSConsoleApp.WSPReference.HelloWorldRequest inValue = new WSConsoleApp.WSPReference.HelloWorldRequest();
            inValue.Body = new WSConsoleApp.WSPReference.HelloWorldRequestBody();
            WSConsoleApp.WSPReference.HelloWorldResponse retVal = ((WSConsoleApp.WSPReference.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsoleApp.WSPReference.HelloWorldResponse> WSConsoleApp.WSPReference.WebService1Soap.HelloWorldAsync(WSConsoleApp.WSPReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsoleApp.WSPReference.HelloWorldResponse> HelloWorldAsync() {
            WSConsoleApp.WSPReference.HelloWorldRequest inValue = new WSConsoleApp.WSPReference.HelloWorldRequest();
            inValue.Body = new WSConsoleApp.WSPReference.HelloWorldRequestBody();
            return ((WSConsoleApp.WSPReference.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSConsoleApp.WSPReference.txtfFileResponse WSConsoleApp.WSPReference.WebService1Soap.txtfFile(WSConsoleApp.WSPReference.txtfFileRequest request) {
            return base.Channel.txtfFile(request);
        }
        
        public string txtfFile(string s) {
            WSConsoleApp.WSPReference.txtfFileRequest inValue = new WSConsoleApp.WSPReference.txtfFileRequest();
            inValue.Body = new WSConsoleApp.WSPReference.txtfFileRequestBody();
            inValue.Body.s = s;
            WSConsoleApp.WSPReference.txtfFileResponse retVal = ((WSConsoleApp.WSPReference.WebService1Soap)(this)).txtfFile(inValue);
            return retVal.Body.txtfFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSConsoleApp.WSPReference.txtfFileResponse> WSConsoleApp.WSPReference.WebService1Soap.txtfFileAsync(WSConsoleApp.WSPReference.txtfFileRequest request) {
            return base.Channel.txtfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSConsoleApp.WSPReference.txtfFileResponse> txtfFileAsync(string s) {
            WSConsoleApp.WSPReference.txtfFileRequest inValue = new WSConsoleApp.WSPReference.txtfFileRequest();
            inValue.Body = new WSConsoleApp.WSPReference.txtfFileRequestBody();
            inValue.Body.s = s;
            return ((WSConsoleApp.WSPReference.WebService1Soap)(this)).txtfFileAsync(inValue);
        }
    }
}
